# Book settings
title: Statistics with Python
author: UQ Student-Staff Partnership


logo: car_sketch_wide.png

html: 
  favicon: car_sketch.png
  home_page_in_navbar : true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_footer: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  google_analytics_id: UA-183782120-1
  
repository:
  url: "https://github.com/uqstatsSSP/uqstatsssp.github.io"
  branch: master
  path_to_book: book

launch_buttons:
  #notebook_interface: "classic" 
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

sphinx:
  extra_extensions:
      - sphinx_inline_tabs
  config:    
    html_show_copyright: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

#bibtex_bibfiles:
#    - references.bib

latex:
 latex_documents:
    targetname: book.tex

#exclude_patterns: [Control/MPC.ipynb]
